name: 'Robocopy'
description: 'Safely mirror project on IIS using Robocopy'
inputs:
  destination:  # id of input
    description: 'Destination directory'
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'